backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "aktualności"
    label: "Aktualności"
    folder: "src/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["news"] }
      - { label: "Obraz Postu", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
  - name: "projekty"
    label: "Projekty"
    folder: "src/projekty"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["projekt"] }
      - { label: "Obraz Posru", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
