backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "aktualności"
    label: "Aktualności"
    folder: "src/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["news"] }
      - { label: "Obraz Postu", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: false, fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: true },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: true },
          { label: 'File Name', name: 'fileName', widget: 'string', required: true }  
        ]
      }
      - { label: 'Galeria', name: 'gallery', widget: 'list', multiple: true, required: false, fields: [
          { label: 'Zdjęcie', name: 'image', widget: 'image' },
          { label: 'Podpis', name: 'caption', widget: 'string' },
        ]
      }
  - name: "projekty"
    label: "Projekty"
    folder: "src/projekty"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["projekt"] }
      - { label: "Obraz Posru", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: false, fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: false },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: false },
          { label: 'File Name', name: 'fileName', widget: 'string', required: false }  
      ]}
      - { label: 'Galeria', name: 'gallery', widget: 'list', multiple: true, required: false, fields: [
          { label: 'Zdjęcie', name: 'image', widget: 'image' },
          { label: 'Podpis', name: 'caption', widget: 'string' },
        ]
      }
  - name: "konkursy"
    label: "Konkursy"
    folder: "src/konkursy"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Id pisane bez spacji", name: "id", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: 'false', fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: false },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: false },
          { label: 'File Name', name: 'fileName', widget: 'string', required: false }  
      ]
    }
  - name: "lsr"
    label: "LSR"
    folder: "/src/lsr"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Id pisane bez spacji", name: "id", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', multiple: 'true', required: 'false', fields: [
            { label: 'File', name: 'file', widget: 'file', multiple: true, required: false },
            { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: false },
            { label: 'File Name', name: 'fileName', widget: 'string', required: false }  
        ]
      }
  - name: "dzialania_statutowe"
    label: "Działania statutowe"
    folder: "src/dzialania_statutowe"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["dzialania_statutowe"] }
      - { label: "Obraz Postu", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: false, fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: true },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: true },
          { label: 'File Name', name: 'fileName', widget: 'string', required: true }  
        ]
      }
      - { label: 'Galeria', name: 'gallery', widget: 'list', multiple: true, required: false, fields: [
          { label: 'Zdjęcie', name: 'image', widget: 'image' },
          { label: 'Podpis', name: 'caption', widget: 'string' },
        ]
      }
  - name: "projekty_inne"
    label: "Projekty Inne"
    folder: "src/projekty_inne"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["projekty_inne"] }
      - { label: "Obraz Postu", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: false, fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: true },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: true },
          { label: 'File Name', name: 'fileName', widget: 'string', required: true }  
        ]
      }
      - { label: 'Galeria', name: 'gallery', widget: 'list', multiple: true, required: false, fields: [
          { label: 'Zdjęcie', name: 'image', widget: 'image' },
          { label: 'Podpis', name: 'caption', widget: 'string' },
        ]
      }
  - name: "projekty_grantowe"
    label: "Projekty Grantowe"
    folder: "src/projekty_grantowe"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["projekty_grantowe"] }
      - { label: "Obraz Postu", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: false, fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: true },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: true },
          { label: 'File Name', name: 'fileName', widget: 'string', required: true }  
        ]
      }
      - { label: 'Galeria', name: 'gallery', widget: 'list', multiple: true, required: false, fields: [
          { label: 'Zdjęcie', name: 'image', widget: 'image' },
          { label: 'Podpis', name: 'caption', widget: 'string' },
        ]
      }
  - name: "rozwoj_lokalny"
    label: "Rozwój Lokalny"
    folder: "src/rozwoj_lokalny"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["rozwoj_lokalny"] }
      - { label: "Obraz Postu", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: false, fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: true },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: true },
          { label: 'File Name', name: 'fileName', widget: 'string', required: true }  
        ]
      }
      - { label: 'Galeria', name: 'gallery', widget: 'list', multiple: true, required: false, fields: [
          { label: 'Zdjęcie', name: 'image', widget: 'image' },
          { label: 'Podpis', name: 'caption', widget: 'string' },
        ]
      }
  - name: "rlks"
    label: "RLKS"
    folder: "src/rlks"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["rlks"] }
      - { label: "Obraz Postu", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: false, fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: true },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: true },
          { label: 'File Name', name: 'fileName', widget: 'string', required: true }  
        ]
      }
      - { label: 'Galeria', name: 'gallery', widget: 'list', multiple: true, required: false, fields: [
          { label: 'Zdjęcie', name: 'image', widget: 'image' },
          { label: 'Podpis', name: 'caption', widget: 'string' },
        ]
      }
  - name: "kbia"
    label: "KBiA"
    folder: "src/kbia"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["kbia"] }
      - { label: "Obraz Postu", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: false, fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: true },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: true },
          { label: 'File Name', name: 'fileName', widget: 'string', required: true }  
        ]
      }
      - { label: 'Galeria', name: 'gallery', widget: 'list', multiple: true, required: false, fields: [
          { label: 'Zdjęcie', name: 'image', widget: 'image' },
          { label: 'Podpis', name: 'caption', widget: 'string' },
        ]
      }
  - name: "dzialaj_lokalnie"
    label: "Działaj Lokalnie"
    folder: "src/dzialaj_lokalnie"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["dzialaj_lokalnie"] }
      - { label: "Obraz Postu", name: "image", widget: "image" }
      - { label: "Alt zdjęcia", name: "imageAlt", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: 'Files', name: 'files', widget: 'list', required: false, fields: [
          { label: 'File', name: 'file', widget: 'file', multiple: true, required: true },
          { label: 'File Type', name: 'fileType', widget: 'select', options: ['pdf', 'docx', 'xlsx'], required: true },
          { label: 'File Name', name: 'fileName', widget: 'string', required: true }  
        ]
      }
      - { label: 'Galeria', name: 'gallery', widget: 'list', multiple: true, required: false, fields: [
          { label: 'Zdjęcie', name: 'image', widget: 'image' },
          { label: 'Podpis', name: 'caption', widget: 'string' },
        ]
      }   
